---
- name: yum | vault
  tags: vault
  yum:
    name=vault
    enablerepo=tkimball83
    state=latest
    update_cache=yes
  register: vault_yum

- name: template | /etc/vault/vault.hcl
  tags: vault
  template:
    src=vault.hcl.j2
    dest=/etc/vault/vault.hcl
    owner=root
    group=root
    mode=0600
  when: vault_yum|success

