---
- name: yum | vault
  tags: vault
  yum:
    name=vault
    enablerepo=tkimball83-{{ tkimball83_pkg }}
    state=latest
    update_cache=yes
  register: vault_yum

- block:
    - name: template | {{ item.dst }}
      template:
        src={{ item.src }}
        dest={{ item.dst }}
        owner=root
        group=root
        mode={{ item.mode }}
      notify:
        - service | vault | restarted
      with_items:
        - { src: vault.hcl.j2, dst: /etc/vault/vault.hcl, mode: '0600' }
        - { src: vault.logrotate.j2, dst: /etc/logrotate.d/vault, mode: '0644' }
        - { src: vault.sysconfig.j2, dst: /etc/sysconfig/vault, mode: '0644' }
    - name: service | vault
      service:
        name=vault
        enabled=yes
        state=started
  tags: vault
  when: vault_yum|success

