---
- name: yum | vault
  tags: vault
  yum:
    name=vault
    enablerepo=tkimball83
    state=latest
    update_cache=yes
  register: vault_yum

- block:
    - name: template | /etc/vault/vault.hcl
      template:
        src=vault.hcl.j2
        dest=/etc/vault/vault.hcl
        owner=root
        group=root
        mode=0600
      notify:
        - service | vault | restarted
    - name: service | vault
      service:
        name=vault
        enabled=yes
        state=started
  tags: vault
  when: vault_yum|success

